title: Explore and Listen to Cuban Cathedral Music
email: gonzalez.aimee.e@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A digital library and interactive map of Cathedral music from Cuba.
baseurl: "/AMS-InstituteTest-Website" # the subpath of your site, e.g. /blog
url: "https://gonzalezaimee.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: gonzalezaimee

theme: minima
