## Description: Download metadata for SCORES from the Google Spreadsheet.
##              Update the SID variable below when the deployment of the
##              Google Apps Script has changed.
##
##              Type "make" in this directory to download the JSON files for the metadata.
##

SID = AKfycbxX4QnIMlHHkgfuu-7E9jRCBQB_R0CZkmI1sQJ5OvmvYhgcOubOJU_h2dQTmUg3AH0

all: download

download: works

works:
	curl -L "https://script.google.com/macros/s/$(SID)/exec?sheet=works" > works.json





